services:
  - type: web
    name: interview-prep-website
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_SQLITE
        value: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: InterviewPrep2024!
      - key: JWT_SECRET
        generateValue: true
